typography_spectrum: 0.0483871
color:
  saturation: 1
  brandStrength: 0.2735798757057637
  lightness: 0.666905
  brandColors:
    - '#A7304F'
    - '#F46D8D'
    - '#F39EB5'
    - '#081028'
    - '#F0CEB7'
  rhythmicContrast: 0.6156027
layout_spectrum: 1
name: Bria Chantel
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Bria Chantel
description: Confessions of a Shopaholic
